-- patch_council_rep_nominations.sql
-- เครื่องมือเก็บรายชื่อ "เสนอตัวแทนสภานักเรียนห้องละ 2 คน" ตามบันทึกข้อความโรงเรียน
-- (ครูที่ปรึกษาสามัญ ม.3-ม.5) — แยกจากระบบสภานักเรียนจริง (council_members/council_applications)
-- ที่ผูกกับตำแหน่งเฉพาะเจาะจงและ workflow นักเรียนสมัครเอง ไม่เข้ากับ use case นี้

CREATE TABLE IF NOT EXISTS public.council_rep_nominations (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  main_room text NOT NULL,
  student_id integer NOT NULL REFERENCES public.students(id) ON DELETE CASCADE,
  nominated_by_teacher_id integer NOT NULL REFERENCES public.teachers(id) ON DELETE CASCADE,
  academic_year text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (main_room, student_id, academic_year)
);
COMMENT ON TABLE public.council_rep_nominations IS
  'รายชื่อนักเรียนที่ครูที่ปรึกษาสามัญเสนอเป็นตัวแทนสภานักเรียน (ห้องละ 2 คน ตามบันทึกข้อความ) — เครื่องมือเก็บรายชื่อเฉพาะ ไม่ผูกกับ council_members/council_applications จริง';

ALTER TABLE public.council_rep_nominations ENABLE ROW LEVEL SECURITY;

-- ครูที่ปรึกษาสามัญของห้องนั้นจัดการรายชื่อห้องตัวเองได้ (insert ต้อง nominated_by_teacher_id = ตัวเอง)
CREATE POLICY "council_rep_nominations_homeroom_teacher" ON public.council_rep_nominations
  FOR ALL TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM homeroom_teachers ht JOIN teachers t ON t.id = ht.teacher_id
      WHERE ht.main_room = council_rep_nominations.main_room
        AND ht.category = 'สามัญ' AND t.profile_id = auth.uid()
    )
    OR (get_user_role() = 'admin')
  )
  WITH CHECK (
    EXISTS (
      SELECT 1 FROM homeroom_teachers ht JOIN teachers t ON t.id = ht.teacher_id
      WHERE ht.main_room = council_rep_nominations.main_room
        AND ht.category = 'สามัญ' AND t.profile_id = auth.uid()
        AND t.id = council_rep_nominations.nominated_by_teacher_id
    )
    OR (get_user_role() = 'admin')
  );
