-- ตารางรายชื่อกลางสำหรับออกเกียรติบัตรแบบหลายรายชื่อ
-- columns: [{key,label,system,removable}] / rows: [{id,student_id,values:{...}}]

create table if not exists public.certificate_recipient_tables (
  id bigint generated by default as identity primary key,
  name text not null check (length(trim(name)) between 1 and 200),
  template_id bigint references public.certificate_templates(id) on delete set null,
  title text,
  columns jsonb not null default '[
    {"key":"student_code","label":"รหัสนักเรียน","system":true,"removable":false},
    {"key":"name","label":"ชื่อ-สกุลนักเรียน","system":true,"removable":false}
  ]'::jsonb,
  rows jsonb not null default '[]'::jsonb,
  created_by_teacher_id integer not null references public.teachers(id) on delete cascade,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint certificate_recipient_tables_columns_array check (jsonb_typeof(columns) = 'array'),
  constraint certificate_recipient_tables_rows_array check (jsonb_typeof(rows) = 'array')
);

create index if not exists certificate_recipient_tables_owner_updated_idx
  on public.certificate_recipient_tables(created_by_teacher_id, updated_at desc);

alter table public.certificate_recipient_tables enable row level security;

drop policy if exists certificate_recipient_tables_owner_all on public.certificate_recipient_tables;
create policy certificate_recipient_tables_owner_all
  on public.certificate_recipient_tables
  for all
  to authenticated
  using (
    created_by_teacher_id in (
      select t.id from public.teachers t where t.profile_id = (select auth.uid())
    )
  )
  with check (
    created_by_teacher_id in (
      select t.id from public.teachers t where t.profile_id = (select auth.uid())
    )
  );

drop policy if exists certificate_recipient_tables_admin_all on public.certificate_recipient_tables;
create policy certificate_recipient_tables_admin_all
  on public.certificate_recipient_tables
  for all
  to authenticated
  using (
    public.get_user_role() = 'admin'
    or exists (
      select 1 from public.profiles p
      where p.id = (select auth.uid()) and p.is_also_admin = true
    )
  )
  with check (
    public.get_user_role() = 'admin'
    or exists (
      select 1 from public.profiles p
      where p.id = (select auth.uid()) and p.is_also_admin = true
    )
  );

grant select, insert, update, delete on table public.certificate_recipient_tables to authenticated;
grant usage, select on sequence public.certificate_recipient_tables_id_seq to authenticated;

comment on table public.certificate_recipient_tables is
  'ตารางรายชื่อผู้รับเกียรติบัตรของครู เก็บโครงสร้างคอลัมน์และแถวแบบ JSON เพื่อออกหลายใบด้วยเทมเพลตเดียว';
