-- patch_attendance_delegation_v2.sql
-- ขยายฟีเจอร์มอบหมายเช็คชื่อแทนครู: เดิม (patch_attendance_delegation.sql) ผูกกับ
-- classroom_leaders (หัวหน้า/รองหัวหน้าห้องที่แอดมินตั้ง) เท่านั้น — ผู้ใช้ขอให้ครูเลือกมอบหมาย
-- นักเรียนคนไหนก็ได้เอง (พิมพ์ค้นหารหัส/ชื่อ) ไม่จำเป็นต้องเป็นหัวหน้าห้องจริง เพื่อกระจายภาระงาน
-- ได้อิสระกว่า — เพิ่มตาราง attendance_delegates เป็นรายชื่อที่ครูจัดการเอง แทนที่การอิง
-- classroom_leaders ใน RLS เดิมทั้งหมด

-- 1) ตารางรายชื่อผู้ได้รับมอบหมาย — ครูเจ้าของห้องเพิ่ม/ลบเองได้อิสระ ไม่ผูกกับหัวหน้าห้องจริง
CREATE TABLE IF NOT EXISTS public.attendance_delegates (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  class_id integer NOT NULL REFERENCES public.classes(id) ON DELETE CASCADE,
  student_id integer NOT NULL REFERENCES public.students(id) ON DELETE CASCADE,
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (class_id, student_id)
);
COMMENT ON TABLE public.attendance_delegates IS
  'รายชื่อนักเรียนที่ครูมอบหมายให้เช็คชื่อแทนได้ต่อห้อง (class_id) — ครูเลือกเองอิสระ ไม่จำเป็นต้องเป็นหัวหน้า/รองหัวหน้าห้องจริงจาก classroom_leaders';

ALTER TABLE public.attendance_delegates ENABLE ROW LEVEL SECURITY;

-- ครูเจ้าของห้อง (หรือ co-teacher/แอดมิน) จัดการรายชื่อผู้ได้รับมอบหมายของห้องตัวเองได้เต็มที่
CREATE POLICY "attendance_delegates_teacher_manage" ON public.attendance_delegates
  FOR ALL TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM classes c
      JOIN master_subjects ms ON ms.id = c.course_id
      JOIN teachers t ON t.id = ms.teacher_id
      WHERE c.id = attendance_delegates.class_id AND t.profile_id = auth.uid()
    )
    OR EXISTS (
      SELECT 1 FROM classes c
      JOIN subject_co_teachers sct ON sct.subject_id = c.course_id
      JOIN teachers t ON t.id = sct.teacher_id
      WHERE c.id = attendance_delegates.class_id AND t.profile_id = auth.uid()
    )
    OR (get_user_role() = 'admin')
  )
  WITH CHECK (
    EXISTS (
      SELECT 1 FROM classes c
      JOIN master_subjects ms ON ms.id = c.course_id
      JOIN teachers t ON t.id = ms.teacher_id
      WHERE c.id = attendance_delegates.class_id AND t.profile_id = auth.uid()
    )
    OR EXISTS (
      SELECT 1 FROM classes c
      JOIN subject_co_teachers sct ON sct.subject_id = c.course_id
      JOIN teachers t ON t.id = sct.teacher_id
      WHERE c.id = attendance_delegates.class_id AND t.profile_id = auth.uid()
    )
    OR (get_user_role() = 'admin')
  );

-- นักเรียนอ่านแถวที่ตัวเองเป็นผู้ได้รับมอบหมายได้ (ใช้แสดงการ์ด "เช็คชื่อแทนครู" ที่หน้าแรกของตัวเอง)
CREATE POLICY "attendance_delegates_self_read" ON public.attendance_delegates
  FOR SELECT TO authenticated
  USING (student_id IN (SELECT id FROM students WHERE profile_id = auth.uid()));

-- 2) แทนที่ policy attendances_delegate_write เดิม (อิง classroom_leaders) ด้วยตัวใหม่ที่เช็ค
--    attendance_delegates แทน — inline EXISTS เหมือนเดิม (ไม่ใช้ SECURITY DEFINER function)
DROP POLICY IF EXISTS "attendances_delegate_write" ON public.attendances;

CREATE POLICY "attendances_delegate_write" ON public.attendances
  FOR ALL TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM classes c
      JOIN attendance_delegates ad ON ad.class_id = c.id
      JOIN students s ON s.id = ad.student_id
      WHERE c.id = attendances.class_id
        AND c.attendance_delegate_enabled = true
        AND s.profile_id = auth.uid()
    )
  )
  WITH CHECK (
    EXISTS (
      SELECT 1 FROM classes c
      JOIN attendance_delegates ad ON ad.class_id = c.id
      JOIN students s ON s.id = ad.student_id
      WHERE c.id = attendances.class_id
        AND c.attendance_delegate_enabled = true
        AND s.profile_id = auth.uid()
    )
  );
