-- Prepared subject catalog for teacher course creation.
-- The catalog is read-only for teachers; selecting an item creates a normal
-- master_subjects row owned by the teacher and keeps catalog_id as provenance.

create table if not exists public.subject_catalog (
  id bigint generated by default as identity primary key,
  catalog_key text not null unique,
  subject_code text,
  subject_name text not null,
  subject_name_arabic text,
  credit numeric,
  subject_group text,
  dept_label text,
  grade_level text,
  curriculum text,
  course_type text,
  learning_area text,
  academic_year integer,
  semester integer,
  source_file text,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists subject_catalog_lookup_idx
  on public.subject_catalog (subject_group, grade_level, subject_code);

create index if not exists subject_catalog_name_idx
  on public.subject_catalog (subject_name);

alter table public.master_subjects
  add column if not exists catalog_id bigint
  references public.subject_catalog(id) on delete set null;

create index if not exists master_subjects_catalog_idx
  on public.master_subjects (catalog_id);

-- Every classroom must belong to a course. The live database was checked
-- before adding this constraint and currently has no null course_id rows.
alter table public.classes
  alter column course_id set not null;

alter table public.subject_catalog enable row level security;

grant select on public.subject_catalog to authenticated;

drop policy if exists subject_catalog_authenticated_read on public.subject_catalog;
create policy subject_catalog_authenticated_read
  on public.subject_catalog
  for select
  to authenticated
  using (is_active is true);

drop policy if exists subject_catalog_admin_manage on public.subject_catalog;
create policy subject_catalog_admin_manage
  on public.subject_catalog
  for all
  to authenticated
  using (
    public.get_user_role() = 'admin'
    or exists (
      select 1
      from public.profiles p
      where p.id = auth.uid()
        and (p.role = 'admin' or p.is_also_admin is true)
    )
  )
  with check (
    public.get_user_role() = 'admin'
    or exists (
      select 1
      from public.profiles p
      where p.id = auth.uid()
        and (p.role = 'admin' or p.is_also_admin is true)
    )
  );
