-- Preserve approved supporters from the closing semester as a one-time
-- renewal entitlement for the new semester. The discount is based on the
-- tier selected in the new semester: 5/10/15/20/25 percent.

create table if not exists public.supporter_renewal_entitlements (
  id bigint generated by default as identity primary key,
  teacher_id integer not null references public.teachers(id) on delete cascade,
  source_academic_year integer not null,
  source_semester integer not null check (source_semester in (1, 2)),
  source_total_amount integer not null check (source_total_amount >= 0),
  source_tier integer not null default 0 check (source_tier between 0 and 5),
  target_academic_year integer not null,
  target_semester integer not null check (target_semester in (1, 2)),
  status text not null default 'available'
    check (status in ('available', 'redeemed', 'expired')),
  redeemed_at timestamptz,
  redeemed_payment_request_id bigint references public.payment_requests(id) on delete set null,
  created_at timestamptz not null default now(),
  unique (teacher_id, target_academic_year, target_semester)
);

alter table public.payment_requests
  add column if not exists supporter_renewal_entitlement_id bigint
    references public.supporter_renewal_entitlements(id) on delete set null,
  add column if not exists donation_tier integer,
  add column if not exists donation_base_amount integer,
  add column if not exists discount_percent integer,
  add column if not exists discount_amount integer;

alter table public.payment_requests
  drop constraint if exists payment_requests_donation_tier_check,
  drop constraint if exists payment_requests_discount_percent_check,
  drop constraint if exists payment_requests_donation_base_amount_check,
  drop constraint if exists payment_requests_discount_amount_check;

alter table public.payment_requests
  add constraint payment_requests_donation_tier_check
    check (donation_tier is null or donation_tier between 1 and 5),
  add constraint payment_requests_discount_percent_check
    check (discount_percent is null or discount_percent between 0 and 25),
  add constraint payment_requests_donation_base_amount_check
    check (donation_base_amount is null or donation_base_amount >= 0),
  add constraint payment_requests_discount_amount_check
    check (discount_amount is null or discount_amount >= 0);

create index if not exists supporter_renewal_entitlements_teacher_term_idx
  on public.supporter_renewal_entitlements (teacher_id, target_academic_year, target_semester);

create index if not exists payment_requests_supporter_renewal_idx
  on public.payment_requests (supporter_renewal_entitlement_id)
  where supporter_renewal_entitlement_id is not null;

alter table public.supporter_renewal_entitlements enable row level security;

grant select on public.supporter_renewal_entitlements to authenticated;

drop policy if exists supporter_renewal_admin_all on public.supporter_renewal_entitlements;
create policy supporter_renewal_admin_all
  on public.supporter_renewal_entitlements
  for all to authenticated
  using (get_user_role() = 'admin')
  with check (get_user_role() = 'admin');

drop policy if exists supporter_renewal_teacher_select on public.supporter_renewal_entitlements;
create policy supporter_renewal_teacher_select
  on public.supporter_renewal_entitlements
  for select to authenticated
  using (
    teacher_id in (
      select t.id from public.teachers t where t.profile_id = auth.uid()
    )
  );

create or replace function public.validate_supporter_renewal_payment_request()
returns trigger
language plpgsql
security definer
set search_path to 'public'
as $function$
declare
  v_entitlement public.supporter_renewal_entitlements;
  v_expected_amount integer;
begin
  if new.supporter_renewal_entitlement_id is null then
    return new;
  end if;

  select * into v_entitlement
  from public.supporter_renewal_entitlements
  where id = new.supporter_renewal_entitlement_id;

  if not found or v_entitlement.teacher_id <> new.teacher_id then
    raise exception 'สิทธิ์ส่วนลดผู้สนับสนุนไม่ถูกต้อง';
  end if;

  if new.package_type <> 'donation'
     or new.donation_tier not between 1 and 5
     or new.donation_base_amount is null
     or new.discount_percent is distinct from new.donation_tier * 5
     or new.discount_amount is distinct from new.donation_base_amount
       - round(new.donation_base_amount * (100 - new.discount_percent) / 100.0)::integer then
    raise exception 'ข้อมูลส่วนลดผู้สนับสนุนไม่ถูกต้อง';
  end if;

  v_expected_amount := round(new.donation_base_amount * (100 - new.discount_percent) / 100.0)::integer;
  if new.amount <> v_expected_amount then
    raise exception 'ยอดชำระสุทธิไม่ตรงกับส่วนลดที่กำหนด';
  end if;

  return new;
end;
$function$;

drop trigger if exists validate_supporter_renewal_payment_request_trigger
  on public.payment_requests;
create trigger validate_supporter_renewal_payment_request_trigger
  before insert or update of teacher_id, package_type, amount,
    supporter_renewal_entitlement_id, donation_tier, donation_base_amount,
    discount_percent, discount_amount
  on public.payment_requests
  for each row
  execute function public.validate_supporter_renewal_payment_request();

create or replace function public.sync_supporter_renewal_entitlement()
returns trigger
language plpgsql
security definer
set search_path to 'public'
as $function$
begin
  if new.supporter_renewal_entitlement_id is null
     or new.status <> 'approved'
     or (tg_op = 'UPDATE' and old.status = 'approved') then
    return new;
  end if;

  update public.supporter_renewal_entitlements
  set status = 'redeemed',
      redeemed_at = coalesce(new.reviewed_at, now()),
      redeemed_payment_request_id = new.id
  where id = new.supporter_renewal_entitlement_id
    and teacher_id = new.teacher_id
    and status = 'available';

  if not found then
    raise exception 'สิทธิ์ส่วนลดผู้สนับสนุนถูกใช้ไปแล้วหรือไม่พร้อมใช้งาน';
  end if;

  return new;
end;
$function$;

drop trigger if exists sync_supporter_renewal_entitlement_trigger
  on public.payment_requests;
create trigger sync_supporter_renewal_entitlement_trigger
  after insert or update of status, reviewed_at
  on public.payment_requests
  for each row
  execute function public.sync_supporter_renewal_entitlement();

create or replace function public.get_supporter_renewal_quote(p_tier_amount integer)
returns jsonb
language plpgsql
security definer
set search_path to 'public'
as $function$
declare
  v_teacher_id integer;
  v_year integer;
  v_semester integer;
  v_entitlement public.supporter_renewal_entitlements;
  v_tier_index integer;
  v_discount_percent integer;
  v_discount_amount integer;
  v_amount integer;
begin
  select t.id into v_teacher_id
  from public.teachers t
  where t.profile_id = auth.uid()
  limit 1;

  if v_teacher_id is null then
    raise exception 'ไม่พบข้อมูลครูของบัญชีนี้';
  end if;

  select value::integer into v_year
  from public.system_config where key = 'academicYear';
  select value::integer into v_semester
  from public.system_config where key = 'semester';

  select * into v_entitlement
  from public.supporter_renewal_entitlements e
  where e.teacher_id = v_teacher_id
    and e.target_academic_year = v_year
    and e.target_semester = v_semester
    and e.status = 'available';

  if not found then
    raise exception 'ไม่พบสิทธิ์ส่วนลดสำหรับภาคเรียนนี้';
  end if;

  with parsed as (
    select row_number() over (order by x.ordinality)::integer as tier_index,
           split_part(trim(x.line), '|', 1)::integer as base_amount
    from regexp_split_to_table(
      coalesce((select value from public.system_config where key = 'donationStickerTiers'), ''),
      E'\n'
    ) with ordinality as x(line, ordinality)
    where split_part(trim(x.line), '|', 1) ~ '^[0-9]+$'
  )
  select p.tier_index into v_tier_index
  from parsed p
  where p.base_amount = p_tier_amount
    and p.tier_index between 1 and 5
  order by p.tier_index
  limit 1;

  if v_tier_index is null then
    raise exception 'ไม่พบระดับการสนับสนุนที่เลือก';
  end if;

  v_discount_percent := least(25, v_tier_index * 5);
  v_amount := round(p_tier_amount * (100 - v_discount_percent) / 100.0)::integer;
  v_discount_amount := p_tier_amount - v_amount;

  return jsonb_build_object(
    'entitlement_id', v_entitlement.id,
    'source_academic_year', v_entitlement.source_academic_year,
    'source_semester', v_entitlement.source_semester,
    'source_total_amount', v_entitlement.source_total_amount,
    'source_tier', v_entitlement.source_tier,
    'target_academic_year', v_year,
    'target_semester', v_semester,
    'tier_index', v_tier_index,
    'base_amount', p_tier_amount,
    'discount_percent', v_discount_percent,
    'discount_amount', v_discount_amount,
    'amount', v_amount
  );
end;
$function$;

create or replace function public.create_supporter_renewal_payment_request(p_tier_amount integer)
returns jsonb
language plpgsql
security definer
set search_path to 'public'
as $function$
declare
  v_teacher_id integer;
  v_quote jsonb;
  v_entitlement_id bigint;
  v_request_id bigint;
  v_status text;
begin
  select t.id into v_teacher_id
  from public.teachers t
  where t.profile_id = auth.uid()
  limit 1;

  if v_teacher_id is null then
    raise exception 'ไม่พบข้อมูลครูของบัญชีนี้';
  end if;

  v_quote := public.get_supporter_renewal_quote(p_tier_amount);
  v_entitlement_id := (v_quote->>'entitlement_id')::bigint;

  select status into v_status
  from public.supporter_renewal_entitlements
  where id = v_entitlement_id
    and teacher_id = v_teacher_id
  for update;

  if v_status <> 'available' then
    raise exception 'สิทธิ์ส่วนลดนี้ไม่พร้อมใช้งานแล้ว';
  end if;

  if exists (
    select 1 from public.payment_requests p
    where p.supporter_renewal_entitlement_id = v_entitlement_id
      and p.status in ('pending', 'approved')
  ) then
    raise exception 'มีคำขอใช้สิทธิ์ส่วนลดนี้อยู่แล้ว';
  end if;

  insert into public.payment_requests (
    teacher_id, package_type, amount, status,
    supporter_renewal_entitlement_id, donation_tier,
    donation_base_amount, discount_percent, discount_amount
  ) values (
    v_teacher_id, 'donation', (v_quote->>'amount')::integer, 'pending',
    v_entitlement_id, (v_quote->>'tier_index')::integer,
    (v_quote->>'base_amount')::integer, (v_quote->>'discount_percent')::integer,
    (v_quote->>'discount_amount')::integer
  ) returning id into v_request_id;

  return v_quote || jsonb_build_object('request_id', v_request_id);
end;
$function$;

revoke all on function public.get_supporter_renewal_quote(integer) from public;
revoke execute on function public.get_supporter_renewal_quote(integer) from anon;
grant execute on function public.get_supporter_renewal_quote(integer) to authenticated;

revoke all on function public.create_supporter_renewal_payment_request(integer) from public;
revoke execute on function public.create_supporter_renewal_payment_request(integer) from anon;
grant execute on function public.create_supporter_renewal_payment_request(integer) to authenticated;

-- Replace the rollover function so the old term is snapshotted before active
-- supporter/quota state is reset.
create or replace function public.admin_start_new_semester(
  p_new_academic_year integer,
  p_new_semester integer
)
returns json
language plpgsql
security definer
set search_path to 'public'
as $function$
declare
  v_old_year integer;
  v_old_sem integer;
  v_old_start date;
  v_min_amount integer := 49;
  v_step_amount integer := 50;
  v_semester_start date := current_date;
  v_entitlements_created integer := 0;
begin
  if get_user_role() <> 'admin' then
    raise exception 'not authorized';
  end if;

  if p_new_academic_year is null or p_new_academic_year <= 0 then
    raise exception 'ปีการศึกษาไม่ถูกต้อง';
  end if;

  if p_new_semester not in (1, 2) then
    raise exception 'ภาคเรียนต้องเป็น 1 หรือ 2';
  end if;

  select value::integer into v_old_year
  from public.system_config where key = 'academicYear';
  select value::integer into v_old_sem
  from public.system_config where key = 'semester';
  select value::date into v_old_start
  from public.system_config where key = 'semester_start';
  select coalesce(value::integer, 49) into v_min_amount
  from public.system_config where key = 'donationMinAmount';
  select coalesce(value::integer, 50) into v_step_amount
  from public.system_config where key = 'donationAmountStep';

  if v_min_amount is null or v_min_amount < 1 then v_min_amount := 49; end if;
  if v_step_amount is null or v_step_amount < 1 then v_step_amount := 50; end if;

  if v_old_year = p_new_academic_year and v_old_sem = p_new_semester then
    raise exception 'ปี/เทอมใหม่เหมือนกับปัจจุบัน ไม่มีอะไรต้องทำ';
  end if;

  with donation_totals as (
    select p.teacher_id,
           sum(coalesce(p.donation_base_amount, p.amount))::integer as total_amount
    from public.payment_requests p
    where p.package_type = 'donation'
      and p.status = 'approved'
      and (v_old_start is null or coalesce(p.reviewed_at, p.created_at)::date >= v_old_start)
    group by p.teacher_id
  )
  insert into public.supporter_renewal_entitlements (
    teacher_id, source_academic_year, source_semester,
    source_total_amount, source_tier,
    target_academic_year, target_semester
  )
  select d.teacher_id,
         v_old_year, v_old_sem,
         d.total_amount,
         case when d.total_amount < v_min_amount then 0
              else least(5, floor((d.total_amount - v_min_amount)::numeric / v_step_amount)::integer + 1)
         end,
         p_new_academic_year, p_new_semester
  from donation_totals d
  where d.total_amount >= v_min_amount
  on conflict (teacher_id, target_academic_year, target_semester) do nothing;

  get diagnostics v_entitlements_created = row_count;

  update public.system_config
  set value = p_new_academic_year::text, updated_at = now()
  where key = 'academicYear';

  update public.system_config
  set value = p_new_semester::text, updated_at = now()
  where key = 'semester';

  insert into public.system_config (key, value, updated_at)
  values ('semester_start', v_semester_start::text, now())
  on conflict (key) do update
    set value = excluded.value, updated_at = excluded.updated_at;

  insert into public.system_config (key, value, updated_at)
  values ('unlimitedTeacherClassCreation', 'true', now())
  on conflict (key) do update
    set value = excluded.value, updated_at = excluded.updated_at;

  update public.teachers_quota
  set total_classes_created = 0,
      is_paid = false,
      package_type = null,
      paid_at = null;

  update public.teachers
  set smart_classroom_free_class_id = null,
      attendance_delegate_free_class_id = null;

  return json_build_object(
    'ok', true,
    'old_academic_year', v_old_year,
    'old_semester', v_old_sem,
    'new_academic_year', p_new_academic_year,
    'new_semester', p_new_semester,
    'semester_start', v_semester_start,
    'supporter_status_reset', true,
    'renewal_entitlements_created', v_entitlements_created,
    'unlimited_teacher_class_creation', true,
    'courses_created', 0,
    'classes_created', 0,
    'students_enrolled', 0,
    'workspace', 'empty'
  );
end;
$function$;

revoke all on function public.admin_start_new_semester(integer, integer) from public;
revoke execute on function public.admin_start_new_semester(integer, integer) from anon;
grant execute on function public.admin_start_new_semester(integer, integer) to authenticated;
