-- Admin management support for school schedules and the subject catalog.
-- The trigger audit is intentionally row-level so manual edits and AI imports
-- are recorded through the same path.

alter table public.master_subjects
  add column if not exists is_active boolean not null default true;

grant select, insert, update, delete on public.subject_catalog to authenticated;
grant select on public.master_subjects to authenticated;

create table if not exists public.admin_academic_audit_logs (
  id bigint generated by default as identity primary key,
  table_name text not null,
  action text not null check (action in ('insert', 'update', 'delete')),
  record_id bigint,
  academic_year integer,
  semester smallint,
  actor_profile_id uuid references public.profiles(id) on delete set null,
  before_data jsonb,
  after_data jsonb,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists admin_academic_audit_logs_lookup_idx
  on public.admin_academic_audit_logs (table_name, created_at desc);

alter table public.admin_academic_audit_logs enable row level security;
grant select on public.admin_academic_audit_logs to authenticated;

drop policy if exists admin_academic_audit_logs_admin_read on public.admin_academic_audit_logs;
create policy admin_academic_audit_logs_admin_read
  on public.admin_academic_audit_logs
  for select to authenticated
  using (
    public.get_user_role() = 'admin'
    or exists (
      select 1 from public.profiles p
      where p.id = auth.uid() and (p.role = 'admin' or p.is_also_admin is true)
    )
  );

create or replace function public.capture_admin_academic_audit()
returns trigger
language plpgsql
security definer
set search_path = pg_catalog, public
as $$
declare
  v_row jsonb;
  v_before jsonb;
  v_after jsonb;
  v_record_id bigint;
  v_year integer;
  v_semester smallint;
  v_actor uuid;
begin
  if tg_op = 'DELETE' then
    v_row := to_jsonb(old);
    v_before := v_row;
    v_after := null;
  elsif tg_op = 'UPDATE' then
    v_before := to_jsonb(old);
    v_after := to_jsonb(new);
    v_row := v_after;
  else
    v_row := to_jsonb(new);
    v_before := null;
    v_after := v_row;
  end if;

  v_record_id := nullif(v_row ->> 'id', '')::bigint;
  v_year := nullif(v_row ->> 'academic_year', '')::integer;
  v_semester := nullif(v_row ->> 'semester', '')::smallint;
  v_actor := nullif(current_setting('request.jwt.claim.sub', true), '')::uuid;

  insert into public.admin_academic_audit_logs
    (table_name, action, record_id, academic_year, semester, actor_profile_id, before_data, after_data, metadata)
  values
    (tg_table_name, lower(tg_op), v_record_id, v_year, v_semester, v_actor, v_before, v_after,
     jsonb_build_object('source', 'database_trigger'));
  if tg_op = 'DELETE' then
    return old;
  end if;
  return new;
end;
$$;

revoke all on function public.capture_admin_academic_audit() from public;

drop trigger if exists teacher_schedules_admin_audit on public.teacher_schedules;
create trigger teacher_schedules_admin_audit
after insert or update or delete on public.teacher_schedules
for each row execute function public.capture_admin_academic_audit();

drop trigger if exists subject_catalog_admin_audit on public.subject_catalog;
create trigger subject_catalog_admin_audit
after insert or update or delete on public.subject_catalog
for each row execute function public.capture_admin_academic_audit();

drop trigger if exists master_subjects_admin_audit on public.master_subjects;
create trigger master_subjects_admin_audit
after insert or update or delete on public.master_subjects
for each row execute function public.capture_admin_academic_audit();
