-- Teacher-side status and server-authoritative preview/submit for live grades.
-- The class card can show "sent" even when a class has no failing students.

create table if not exists public.regrade_class_submissions (
  id bigint generated by default as identity primary key,
  class_id integer not null references public.classes(id) on delete cascade,
  teacher_id integer not null references public.teachers(id) on delete cascade,
  academic_year integer not null,
  semester integer not null check (semester in (1, 2)),
  status text not null default 'submitted' check (status in ('submitted')),
  failing_count integer not null default 0 check (failing_count >= 0),
  submitted_count integer not null default 0 check (submitted_count >= 0),
  submitted_by uuid references auth.users(id),
  submitted_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (class_id)
);

alter table public.regrade_class_submissions enable row level security;

drop policy if exists "teachers can view own regrade class submissions" on public.regrade_class_submissions;
create policy "teachers can view own regrade class submissions"
  on public.regrade_class_submissions
  for select
  to authenticated
  using (
    exists (
      select 1
      from public.classes c
      join public.master_subjects ms on ms.id = c.course_id
      join public.teachers t on t.id = ms.teacher_id
      where c.id = regrade_class_submissions.class_id
        and regrade_class_submissions.teacher_id = t.id
        and t.profile_id = (select auth.uid())
    )
  );

revoke all on table public.regrade_class_submissions from public, anon, authenticated;

create or replace function public.preview_class_grades_to_regrade(p_class_id integer)
returns jsonb
language plpgsql
security definer
set search_path to 'public'
as $function$
declare
  v_teacher_id integer;
  v_subject_code text;
  v_subject_name text;
  v_subject_group text;
  v_grade_level text;
  v_class_name text;
  v_class_academic_year integer;
  v_class_semester integer;
  v_category text;
  v_result jsonb;
begin
  select ms.teacher_id, ms.subject_code, ms.subject_name, ms.subject_group, ms.grade_level,
         c.class_name, c.academic_year, c.semester
  into v_teacher_id, v_subject_code, v_subject_name, v_subject_group, v_grade_level,
       v_class_name, v_class_academic_year, v_class_semester
  from public.classes c
  join public.master_subjects ms on ms.id = c.course_id
  where c.id = p_class_id;

  if v_teacher_id is null then
    raise exception 'ไม่พบวิชานี้';
  end if;
  if not exists (
    select 1 from public.teachers t
    where t.id = v_teacher_id and t.profile_id = auth.uid()
  ) then
    raise exception 'not authorized';
  end if;

  v_class_academic_year := coalesce(v_class_academic_year, (
    select nullif(value, '')::integer from public.system_config where key = 'academicYear'
  ));
  v_class_semester := coalesce(v_class_semester, (
    select nullif(value, '')::integer from public.system_config where key = 'semester'
  ));

  v_category := case when v_subject_group like 'AGM%' then 'ศาสนา' else 'สามัญ' end;

  with score_limits as (
    select csc.class_id,
           sum(coalesce(csc.max_score, 0)) as max_total,
           count(*) as score_column_count
    from public.class_score_columns csc
    where csc.class_id = p_class_id
      and coalesce(csc.column_type, 'regular') not in ('bonus', 'override')
      and coalesce(csc.assignment_type, '') <> 'คะแนนพิเศษ'
    group by csc.class_id
  ),
  score_totals as (
    select csc.class_id,
           ss.student_id,
           sum(coalesce(ss.final_score, ss.original_score, 0)) as raw_total,
           count(*) filter (where coalesce(ss.final_score, ss.original_score) is not null) as scored_count
    from public.class_score_columns csc
    join public.student_scores ss on ss.assignment_id = csc.id
    where csc.class_id = p_class_id
      and coalesce(csc.column_type, 'regular') not in ('bonus', 'override')
      and coalesce(csc.assignment_type, '') <> 'คะแนนพิเศษ'
    group by csc.class_id, ss.student_id
  ),
  failing as (
    select en.student_id,
           s.full_name,
           s.student_code,
           case
             when nullif(trim(en.special_result), '') is not null then trim(en.special_result)
             when coalesce(sl.max_total, 0) = 0 then '0'
             else '0'
           end as grade_failed_at,
           nullif(trim(en.special_result), '') as special_result,
           round(coalesce(st.raw_total, 0))::numeric as raw_total,
           coalesce(sl.max_total, 0)::numeric as max_total
    from public.class_students en
    join public.students s on s.id = en.student_id
    left join score_limits sl on true
    left join score_totals st on st.class_id = p_class_id and st.student_id = en.student_id
    where en.class_id = p_class_id
      and en.is_active is not false
      and (
        nullif(trim(en.special_result), '') is not null
        or (
          coalesce(sl.score_column_count, 0) > 0
          and coalesce(st.scored_count, 0) >= sl.score_column_count
          and (
            coalesce(sl.max_total, 0) = 0
            or (round(coalesce(st.raw_total, 0)) / nullif(sl.max_total, 0) * 100) < 50
          )
        )
      )
  )
  select jsonb_build_object(
    'ok', true,
    'class_id', p_class_id,
    'class_name', v_class_name,
    'subject_code', v_subject_code,
    'subject_name', v_subject_name,
    'category', v_category,
    'academic_year', v_class_academic_year,
    'semester', v_class_semester,
    'already_submitted', exists (
      select 1 from public.regrade_class_submissions rcs where rcs.class_id = p_class_id
    ),
    'students', coalesce((
      select jsonb_agg(jsonb_build_object(
        'student_id', f.student_id,
        'full_name', f.full_name,
        'student_code', f.student_code,
        'grade_failed_at', f.grade_failed_at,
        'special_result', f.special_result,
        'raw_total', f.raw_total,
        'max_total', f.max_total
      ) order by f.full_name)
      from failing f
    ), '[]'::jsonb)
  ) into v_result;

  return v_result;
end;
$function$;

create or replace function public.get_teacher_regrade_submission_statuses(p_class_ids integer[])
returns jsonb
language plpgsql
security definer
set search_path to 'public'
as $function$
begin
  if not exists (select 1 from public.teachers t where t.profile_id = auth.uid()) then
    raise exception 'not authorized';
  end if;

  return coalesce((
    select jsonb_agg(jsonb_build_object(
      'class_id', c.id,
      'status', rcs.status,
      'failing_count', coalesce(rcs.failing_count, 0),
      'submitted_count', coalesce(rcs.submitted_count, 0),
      'submitted_at', rcs.submitted_at
    ) order by c.id)
    from public.classes c
    join public.master_subjects ms on ms.id = c.course_id
    join public.teachers t on t.id = ms.teacher_id and t.profile_id = auth.uid()
    left join public.regrade_class_submissions rcs on rcs.class_id = c.id
    where c.id = any(coalesce(p_class_ids, '{}'::integer[]))
  ), '[]'::jsonb);
end;
$function$;

create or replace function public.submit_class_grades_to_regrade(
  p_class_id integer,
  p_failing jsonb default '[]'::jsonb
)
returns json
language plpgsql
security definer
set search_path to 'public'
as $function$
declare
  v_preview jsonb;
  v_teacher_id integer;
  v_inserted integer := 0;
  v_total_failing integer := 0;
  v_academic_year integer;
  v_semester integer;
  v_item jsonb;
  v_new_id bigint;
  v_semester_key text;
begin
  v_preview := public.preview_class_grades_to_regrade(p_class_id);
  v_total_failing := jsonb_array_length(coalesce(v_preview->'students', '[]'::jsonb));
  v_academic_year := nullif(v_preview->>'academic_year', '')::integer;
  v_semester := nullif(v_preview->>'semester', '')::integer;
  v_semester_key := v_semester::text || '/' || v_academic_year::text;

  select ms.teacher_id into v_teacher_id
  from public.classes c
  join public.master_subjects ms on ms.id = c.course_id
  where c.id = p_class_id;

  for v_item in select * from jsonb_array_elements(coalesce(v_preview->'students', '[]'::jsonb))
  loop
    v_new_id := null;
    insert into public.regrade_subjects
      (student_id, teacher_id, subject_code, subject_name, category, class_level, semester,
       grade_failed_at, status, source, teacher_name_raw, created_by)
    select
      (v_item->>'student_id')::integer,
      ms.teacher_id,
      ms.subject_code,
      ms.subject_name,
      case when ms.subject_group like 'AGM%' then 'ศาสนา' else 'สามัญ' end,
      ms.grade_level,
      v_semester_key,
      nullif(trim(v_item->>'grade_failed_at'), ''),
      'ยังไม่แจ้ง',
      'live',
      t.full_name,
      auth.uid()
    from public.classes c
    join public.master_subjects ms on ms.id = c.course_id
    join public.teachers t on t.id = ms.teacher_id
    where c.id = p_class_id
    on conflict (student_id, subject_code, semester) do nothing
    returning id into v_new_id;
    if v_new_id is not null then v_inserted := v_inserted + 1; end if;
  end loop;

  insert into public.regrade_class_submissions
    (class_id, teacher_id, academic_year, semester, status, failing_count,
     submitted_count, submitted_by, submitted_at, updated_at)
  values
    (p_class_id, v_teacher_id, v_academic_year, v_semester, 'submitted',
     v_total_failing, v_inserted, auth.uid(), now(), now())
  on conflict (class_id) do update set
    teacher_id = excluded.teacher_id,
    academic_year = excluded.academic_year,
    semester = excluded.semester,
    status = 'submitted',
    failing_count = excluded.failing_count,
    submitted_count = excluded.submitted_count,
    submitted_by = excluded.submitted_by,
    submitted_at = excluded.submitted_at,
    updated_at = now();

  return json_build_object(
    'ok', true,
    'total_failing', v_total_failing,
    'submitted', v_inserted,
    'submitted_at', now()
  );
end;
$function$;

revoke all on function public.preview_class_grades_to_regrade(integer) from public, anon;
grant execute on function public.preview_class_grades_to_regrade(integer) to authenticated;
revoke all on function public.get_teacher_regrade_submission_statuses(integer[]) from public, anon;
grant execute on function public.get_teacher_regrade_submission_statuses(integer[]) to authenticated;
revoke all on function public.submit_class_grades_to_regrade(integer, jsonb) from public, anon;
grant execute on function public.submit_class_grades_to_regrade(integer, jsonb) to authenticated;
