-- Council YLA operational module
-- Stores event execution, participant progress, attendance, assessment, and result records.

create table if not exists public.council_yla_events (
  id bigint generated by default as identity primary key,
  academic_year integer not null,
  event_code text not null default 'YLA',
  title text not null,
  description text,
  status text not null default 'draft',
  start_date date,
  end_date date,
  location text,
  capacity integer,
  created_by_teacher_id integer references public.teachers(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint council_yla_events_status_check check (status in ('draft', 'planned', 'active', 'completed', 'cancelled')),
  constraint council_yla_events_capacity_check check (capacity is null or capacity > 0),
  constraint council_yla_events_date_check check (end_date is null or start_date is null or end_date >= start_date)
);

create table if not exists public.council_yla_participants (
  id bigint generated by default as identity primary key,
  event_id bigint not null references public.council_yla_events(id) on delete cascade,
  student_id integer not null references public.students(id) on delete cascade,
  application_id bigint references public.council_applications(id) on delete set null,
  status text not null default 'registered',
  registered_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint council_yla_participants_status_check check (status in ('invited', 'registered', 'completed', 'withdrawn')),
  constraint council_yla_participants_unique unique (event_id, student_id)
);

create table if not exists public.council_yla_attendance (
  id bigint generated by default as identity primary key,
  event_id bigint not null references public.council_yla_events(id) on delete cascade,
  student_id integer not null references public.students(id) on delete cascade,
  session_label text not null default 'กิจกรรมหลัก',
  attendance_state text not null default 'present',
  checked_in_at timestamptz,
  note text,
  recorded_by_teacher_id integer references public.teachers(id) on delete set null,
  updated_at timestamptz not null default now(),
  constraint council_yla_attendance_state_check check (attendance_state in ('present', 'late', 'excused_leave', 'unexcused_absence')),
  constraint council_yla_attendance_unique unique (event_id, student_id, session_label)
);

create table if not exists public.council_yla_criteria (
  id bigint generated by default as identity primary key,
  event_id bigint not null references public.council_yla_events(id) on delete cascade,
  name text not null,
  weight numeric(6,2) not null default 20,
  sort_order integer not null default 0,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  constraint council_yla_criteria_weight_check check (weight > 0),
  constraint council_yla_criteria_unique_name unique (event_id, name)
);

create table if not exists public.council_yla_scores (
  id bigint generated by default as identity primary key,
  event_id bigint not null references public.council_yla_events(id) on delete cascade,
  student_id integer not null references public.students(id) on delete cascade,
  criterion_id bigint not null references public.council_yla_criteria(id) on delete cascade,
  score numeric(6,2) not null default 0,
  comment text,
  scored_by_teacher_id integer references public.teachers(id) on delete set null,
  updated_at timestamptz not null default now(),
  constraint council_yla_scores_score_check check (score >= 0),
  constraint council_yla_scores_unique unique (event_id, student_id, criterion_id)
);

create table if not exists public.council_yla_results (
  id bigint generated by default as identity primary key,
  event_id bigint not null references public.council_yla_events(id) on delete cascade,
  student_id integer not null references public.students(id) on delete cascade,
  total_score numeric(8,2),
  strengths text,
  areas_to_develop text,
  recommended_position text,
  recommended_division text,
  final_result text not null default 'pending',
  finalized_by_teacher_id integer references public.teachers(id) on delete set null,
  finalized_at timestamptz,
  updated_at timestamptz not null default now(),
  constraint council_yla_results_final_result_check check (final_result in ('pending', 'pass', 'fail', 'withdrawn')),
  constraint council_yla_results_unique unique (event_id, student_id)
);

create index if not exists council_yla_events_year_status_idx
  on public.council_yla_events (academic_year, status, start_date desc);
create index if not exists council_yla_participants_event_status_idx
  on public.council_yla_participants (event_id, status, student_id);
create index if not exists council_yla_attendance_event_student_idx
  on public.council_yla_attendance (event_id, student_id, session_label);
create index if not exists council_yla_scores_event_student_idx
  on public.council_yla_scores (event_id, student_id, criterion_id);
create index if not exists council_yla_results_event_result_idx
  on public.council_yla_results (event_id, final_result, student_id);

alter table public.council_yla_events enable row level security;
alter table public.council_yla_participants enable row level security;
alter table public.council_yla_attendance enable row level security;
alter table public.council_yla_criteria enable row level security;
alter table public.council_yla_scores enable row level security;
alter table public.council_yla_results enable row level security;

grant select, insert, update, delete on public.council_yla_events to authenticated;
grant select, insert, update, delete on public.council_yla_participants to authenticated;
grant select, insert, update, delete on public.council_yla_attendance to authenticated;
grant select, insert, update, delete on public.council_yla_criteria to authenticated;
grant select, insert, update, delete on public.council_yla_scores to authenticated;
grant select, insert, update, delete on public.council_yla_results to authenticated;
grant usage, select on sequence
  public.council_yla_events_id_seq,
  public.council_yla_participants_id_seq,
  public.council_yla_attendance_id_seq,
  public.council_yla_criteria_id_seq,
  public.council_yla_scores_id_seq,
  public.council_yla_results_id_seq
  to authenticated;

drop policy if exists council_yla_events_authenticated_read on public.council_yla_events;
create policy council_yla_events_authenticated_read on public.council_yla_events
  for select to authenticated using (status <> 'cancelled');
drop policy if exists council_yla_events_staff_write on public.council_yla_events;
create policy council_yla_events_staff_write on public.council_yla_events
  for all to authenticated
  using (get_user_role() = any (array['admin', 'teacher']))
  with check (get_user_role() = any (array['admin', 'teacher']));

drop policy if exists council_yla_participants_self_read on public.council_yla_participants;
create policy council_yla_participants_self_read on public.council_yla_participants
  for select to authenticated
  using (exists (select 1 from public.students s where s.id = council_yla_participants.student_id and s.profile_id = (select auth.uid())));
drop policy if exists council_yla_participants_staff_access on public.council_yla_participants;
create policy council_yla_participants_staff_access on public.council_yla_participants
  for all to authenticated
  using (get_user_role() = any (array['admin', 'teacher']))
  with check (get_user_role() = any (array['admin', 'teacher']));

drop policy if exists council_yla_attendance_self_read on public.council_yla_attendance;
create policy council_yla_attendance_self_read on public.council_yla_attendance
  for select to authenticated
  using (exists (select 1 from public.students s where s.id = council_yla_attendance.student_id and s.profile_id = (select auth.uid())));
drop policy if exists council_yla_attendance_staff_access on public.council_yla_attendance;
create policy council_yla_attendance_staff_access on public.council_yla_attendance
  for all to authenticated
  using (get_user_role() = any (array['admin', 'teacher']))
  with check (get_user_role() = any (array['admin', 'teacher']));

drop policy if exists council_yla_criteria_authenticated_read on public.council_yla_criteria;
create policy council_yla_criteria_authenticated_read on public.council_yla_criteria
  for select to authenticated using (is_active = true);
drop policy if exists council_yla_criteria_staff_access on public.council_yla_criteria;
create policy council_yla_criteria_staff_access on public.council_yla_criteria
  for all to authenticated
  using (get_user_role() = any (array['admin', 'teacher']))
  with check (get_user_role() = any (array['admin', 'teacher']));

drop policy if exists council_yla_scores_self_read on public.council_yla_scores;
create policy council_yla_scores_self_read on public.council_yla_scores
  for select to authenticated
  using (exists (select 1 from public.students s where s.id = council_yla_scores.student_id and s.profile_id = (select auth.uid())));
drop policy if exists council_yla_scores_staff_access on public.council_yla_scores;
create policy council_yla_scores_staff_access on public.council_yla_scores
  for all to authenticated
  using (get_user_role() = any (array['admin', 'teacher']))
  with check (get_user_role() = any (array['admin', 'teacher']));

drop policy if exists council_yla_results_self_read on public.council_yla_results;
create policy council_yla_results_self_read on public.council_yla_results
  for select to authenticated
  using (exists (select 1 from public.students s where s.id = council_yla_results.student_id and s.profile_id = (select auth.uid())));
drop policy if exists council_yla_results_staff_access on public.council_yla_results;
create policy council_yla_results_staff_access on public.council_yla_results
  for all to authenticated
  using (get_user_role() = any (array['admin', 'teacher']))
  with check (get_user_role() = any (array['admin', 'teacher']));
