-- Register academic terms independently from courses/classes.
-- A new term must be selectable even while its workspace is still empty.
create table if not exists public.academic_terms (
  id bigint generated by default as identity primary key,
  academic_year integer not null check (academic_year > 0),
  semester integer not null check (semester in (1, 2)),
  start_date date,
  end_date date,
  status text not null default 'active' check (status in ('planned', 'active', 'closed')),
  is_current boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (academic_year, semester)
);

create unique index if not exists academic_terms_current_idx
  on public.academic_terms (is_current)
  where is_current = true;

create index if not exists academic_terms_order_idx
  on public.academic_terms (academic_year desc, semester desc);

alter table public.academic_terms enable row level security;

drop policy if exists academic_terms_select_authenticated on public.academic_terms;
create policy academic_terms_select_authenticated
  on public.academic_terms for select to authenticated
  using (true);

drop policy if exists academic_terms_admin_insert on public.academic_terms;
create policy academic_terms_admin_insert
  on public.academic_terms for insert to authenticated
  with check (get_user_role() = 'admin');

drop policy if exists academic_terms_admin_update on public.academic_terms;
create policy academic_terms_admin_update
  on public.academic_terms for update to authenticated
  using (get_user_role() = 'admin')
  with check (get_user_role() = 'admin');

-- Seed the real current term before installing the synchronisation trigger.
insert into public.academic_terms (
  academic_year, semester, start_date, end_date, status, is_current
)
select
  coalesce((max(value) filter (where key = 'academicYear'))::integer, 2569),
  coalesce((max(value) filter (where key = 'semester'))::integer, 1),
  (max(value) filter (where key = 'semester_start'))::date,
  (max(value) filter (where key = 'semester_end'))::date,
  'active', true
from public.system_config
on conflict (academic_year, semester) do update set
  start_date = coalesce(excluded.start_date, academic_terms.start_date),
  end_date = coalesce(excluded.end_date, academic_terms.end_date),
  status = 'active',
  is_current = true,
  updated_at = now();

-- Keep the registry aligned when the existing rollover RPC updates system_config.
create or replace function public.sync_academic_term_registry()
returns trigger
language plpgsql
security definer
set search_path to 'public'
as $function$
declare
  v_year integer;
  v_sem integer;
  v_start date;
  v_end date;
begin
  select
    (max(value) filter (where key = 'academicYear'))::integer,
    (max(value) filter (where key = 'semester'))::integer,
    (max(value) filter (where key = 'semester_start'))::date,
    (max(value) filter (where key = 'semester_end'))::date
  into v_year, v_sem, v_start, v_end
  from public.system_config;

  if v_year is null or v_year <= 0 or v_sem not in (1, 2) then
    return new;
  end if;

  update public.academic_terms
  set is_current = false,
      status = case when status = 'active' then 'closed' else status end,
      updated_at = now()
  where is_current = true
    and not (academic_year = v_year and semester = v_sem);

  insert into public.academic_terms (
    academic_year, semester, start_date, end_date, status, is_current, updated_at
  ) values (
    v_year, v_sem, v_start, v_end, 'active', true, now()
  )
  on conflict (academic_year, semester) do update set
    start_date = coalesce(excluded.start_date, academic_terms.start_date),
    end_date = coalesce(excluded.end_date, academic_terms.end_date),
    status = 'active',
    is_current = true,
    updated_at = now();

  return new;
end;
$function$;

drop trigger if exists system_config_sync_academic_term on public.system_config;
create trigger system_config_sync_academic_term
after insert or update of value on public.system_config
for each row
when (new.key in ('academicYear', 'semester', 'semester_start', 'semester_end'))
execute function public.sync_academic_term_registry();

revoke all on function public.sync_academic_term_registry() from public, anon, authenticated;

-- Student score history may request a registered historical term, while the
-- original RPC remains a current-term-only compatibility entry point.
create or replace function public.get_student_enrolled_classes_for_term(
  p_student_id integer,
  p_academic_year integer,
  p_semester integer
)
returns jsonb
language sql
security definer
set search_path to 'public'
as $function$
  select coalesce(jsonb_agg(
    jsonb_build_object(
      'id', c.id,
      'class_name', c.class_name,
      'skill_group', c.skill_group,
      'google_sheet_id', c.google_sheet_id,
      'subject_group_override', c.subject_group_override,
      'academic_year', c.academic_year,
      'semester', c.semester,
      'day1_date', c.day1_date,
      'day2_date', c.day2_date,
      'day3_date', c.day3_date,
      'day4_date', c.day4_date,
      'day5_date', c.day5_date,
      'day6_date', c.day6_date,
      'master_subjects', case when ms.id is null then null else jsonb_build_object(
        'id', ms.id,
        'subject_code', ms.subject_code,
        'subject_name', ms.subject_name,
        'dept', ms.dept,
        'grade_level', ms.grade_level,
        'credit', ms.credit,
        'teacher_id', ms.teacher_id,
        'subject_group', ms.subject_group,
        'teachers', case when t.id is null then null else jsonb_build_object(
          'id', t.id, 'full_name', t.full_name, 'phone', t.phone,
          'image_url', t.image_url, 'category', t.category
        ) end
      ) end
    ) order by c.class_name, c.id
  ), '[]'::jsonb)
  from public.students s
  join public.class_students cs on cs.student_id = s.id
  join public.classes c on c.id = cs.class_id
  left join public.master_subjects ms on ms.id = c.course_id
  left join public.teachers t on t.id = ms.teacher_id
  where s.id = p_student_id
    and s.profile_id = auth.uid()
    and s.is_active = true
    and exists (
      select 1 from public.academic_terms at
      where at.academic_year = p_academic_year
        and at.semester = p_semester
    )
    and c.academic_year = p_academic_year
    and c.semester = p_semester;
$function$;

create or replace function public.get_student_enrolled_classes(p_student_id integer)
returns jsonb
language sql
security definer
set search_path to 'public'
as $function$
  with current_term as (
    select
      coalesce((max(value) filter (where key = 'academicYear'))::integer, 2569) as academic_year,
      coalesce((max(value) filter (where key = 'semester'))::integer, 1) as semester
    from public.system_config
  )
  select public.get_student_enrolled_classes_for_term(
    p_student_id, current_term.academic_year, current_term.semester
  )
  from current_term;
$function$;

revoke all on function public.get_student_enrolled_classes_for_term(integer, integer, integer) from public, anon;
grant execute on function public.get_student_enrolled_classes_for_term(integer, integer, integer) to authenticated;
revoke all on function public.get_student_enrolled_classes(integer) from public, anon;
grant execute on function public.get_student_enrolled_classes(integer) to authenticated;
