-- Remember confirmed teacher names from external school schedule files.
-- This table is intentionally admin-only: aliases affect future imports and
-- must never be writable by a normal teacher account.

create table if not exists public.teacher_name_aliases (
  id bigint generated by default as identity primary key,
  teacher_id integer not null references public.teachers(id) on delete cascade,
  source_name text not null,
  normalized_name text not null,
  source_system text not null default 'school_schedule',
  created_by uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (source_system, normalized_name)
);

create index if not exists teacher_name_aliases_teacher_idx
  on public.teacher_name_aliases (teacher_id);

alter table public.teacher_name_aliases enable row level security;

grant select, insert, update on public.teacher_name_aliases to authenticated;

drop policy if exists teacher_name_aliases_admin_read on public.teacher_name_aliases;
create policy teacher_name_aliases_admin_read
  on public.teacher_name_aliases
  for select to authenticated
  using (
    public.get_user_role() = 'admin'
    or exists (
      select 1 from public.profiles p
      where p.id = auth.uid() and p.is_also_admin is true
    )
  );

drop policy if exists teacher_name_aliases_admin_write on public.teacher_name_aliases;
create policy teacher_name_aliases_admin_write
  on public.teacher_name_aliases
  for all to authenticated
  using (
    public.get_user_role() = 'admin'
    or exists (
      select 1 from public.profiles p
      where p.id = auth.uid() and p.is_also_admin is true
    )
  )
  with check (
    public.get_user_role() = 'admin'
    or exists (
      select 1 from public.profiles p
      where p.id = auth.uid() and p.is_also_admin is true
    )
  );
